joanpablo/reactive_forms

example/.gitignore, example/.metadata, example/android/.gitignore, example/android/app/build.gradle, example/android/build.gradle, example/android/gradle.properties, example/android/settings.gradle, example/ios/Flutter/AppFrameworkInfo.plist, example/ios/Runner.xcodeproj/project.pbxproj, example/pubspec.yaml
Hi! Thanks for your work.
I would like to practice a little in form usage.
I came from `flutter_form_bloc`. This project is not supported anymore. At least there is no activity from author.
So I'd like to implement examples like this https://giancarlocode.github.io/form_bloc/#/
If you are ok with this approach I'll try to improve examples)
There is my first PR aimed to update the `example` to run on latest ios simulator
=> example update to run on latest ios simulator

.vscode/launch.json, lib/src/value_accessors/time_of_day_value_accessor.dart
Sup bro, just adding a little improvement :)
=> fix(time of day string): Improving time of day model to view string.

lib/src/widgets/reactive_checkbox.dart, lib/src/widgets/reactive_checkbox_list_tile.dart, test/src/widgets/reactive_checkbox_list_tile_test.dart, test/src/widgets/reactive_checkbox_list_tile_testing_widget.dart, test/src/widgets/reactive_checkbox_test.dart, test/src/widgets/reactive_checkbox_testing_widget.dart
=> tristate support for checkbox and checkbox list tile

example/lib/samples/date_picker_sample.dart, example/pubspec.yaml, lib/reactive_forms.dart, lib/src/value_accessors/formatted_datetime_value_accessor.dart, pubspec.yaml, test/src/value_accessors/formatted_datetime_value_accessor_test.dart
=> Formatted DateTime Value Accessor

README.md, example/lib/drawer.dart, example/lib/main.dart, example/lib/samples/reactive_form_widgets_sample.dart, example/pubspec.yaml
=> reactive form widgets example and readme

lib/src/models/models.dart, lib/src/validators/validators.dart
=> form control validators type

lib/src/models/models.dart, lib/src/validators/email_validator.dart, lib/src/validators/validators.dart, test/src/models/form_group_test.dart, test/src/validators/email_validator_test.dart
I fixed the tests.
Could you add test pipeline to the repo?
=> less dynamicity part 2

README.md
Added more reactive widgets wrapper
=> more-reactive-widgets2

README.md
Hi @joanpablo 
Pretty light PR
=> readme update with new inputs

example/lib/samples/array_sample.dart
added delete option to illustrate how to work with arrays
=> array sample - delete option

lib/src/models/models.dart, test/src/models/form_group_test.dart
=> assertion on control naming

example/lib/samples/complex_sample.dart
=> dropdown complex sample

.github/PULL_REQUEST_TEMPLATE.MD
Close: #323 
- Add option to close automatically a issue
- Require description
- Checklist to actions to do from contributor
=> chore: Create a pull request template

example/pubspec.yaml, pubspec.yaml
Close #348 
Update intl package to v0.18.0
=> Update intl package

lib/reactive_forms.dart
=> fix duplicate export

test/src/validators/any_validator_test.dart, test/src/validators/compare_validator_test.dart, test/src/validators/min_length_validator_test.dart
Validator test coverage improvement
=> Validator test coverage improvement

README.md
Close #388
Update README.md with the new syntax that replaces the deprecated `ValidatorFunction`
=> Update README.md replacing deprecated ValidatorFunction

lib/src/models/models.dart
=> Fix for #386

README.md
Added example about how to test whole form to readme
=> docs: update readme with testing examples

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/documentation.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md
Close: #322 
- Get minimal info
- Set automatic label
- Create 4 categories: bug, new feature, documentation and question
=> chore: Add issue templates
